routes/web.php
<?php

use App\Http\Controllers\Admin\AdminBanUserController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\AdminUserActionsController;
use App\Http\Controllers\Users\DashController;
use App\Http\Controllers\Users\UserController;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\URL;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

try {

    Route::get('/', function () {
        return view('welcome');
    });
    /*
    |--------------------------------------------------------------------------
    | Site web Routes
    |--------------------------------------------------------------------------
    |
    */
    Route::middleware(['auth', 'verified'])->group(function () {

        /*
        |-------------------------------------------------------------------------------
        | Admin section
        |-------------------------------------------------------------------------------
        | Prefix:         admin/ OR .admin
        | Controller:     Admin/AdminController
        | Method:         MIXED
        | Description:    Admin actions
        */
        Route::prefix('admin')
            ->middleware(['is_admin'])
            ->name('admin.')
            ->group(function () {

                Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');

                // User actions
                Route::get('/view_user/{user_id}', [AdminUserActionsController::class, 'viewUser'])->name('view_user')->where('user_id', '[0-9]+');
                Route::get('/view_users', [AdminUserActionsController::class, 'viewAllUsers'])->name('view_users');
                Route::post('/find_user', [AdminUserActionsController::class, 'findUser'])->name('find_user');
                Route::get('/delete_user/{user_id}', [AdminUserActionsController::class, 'deleteUser'])->name('delete_user')->where('user_id', '[0-9]+');
                Route::get('/user_status/{user_id}', [AdminUserActionsController::class, 'changeUserStatus'])->name('user_status')->where('user_id', '[0-9]+');

                // Clone users
                Route::get('/clone_user/{user_id}', [AdminUserActionsController::class, 'cloneUser'])->name('clone_user')->where('user_id', '[0-9]+');

                // Banned users
                Route::post('/ban_user', [AdminBanUserController::class, 'banUser'])->name('ban_user');
                Route::get('/unban_user/{user_id}', [AdminBanUserController::class, 'unbanUser'])->name('unban_user')->where('user_id', '[0-9]+');
                Route::get('/view_banned_users', [AdminBanUserController::class, 'viewAllBannedUsers'])->name('view_banned_users');

            });

        /*
        |-------------------------------------------------------------------------------
        | User section
        |-------------------------------------------------------------------------------
        | Prefix:         user/ OR .user
        | Controller:     Users/UserController
        | Method:         MIXED
        | Description:    User actions
        */
        Route::prefix('user')
            ->name('user.')
            ->middleware(['forbid-banned-user', 'is_online'])
            ->group(function () {

                // General routes and settings
                Route::get('/dashboard', [DashController::class, 'index'])->name('dashboard');
                Route::get('/user_profile', [UserController::class, 'viewProfile'])->name('user_profile');
                Route::get('/user_change_password', [UserController::class, 'changePassword'])->name('user_change_password');
                Route::post('/user_save_password', [UserController::class, 'savePassword'])->name('user_save_password');
                Route::post('/user_change_visibility', [UserController::class, 'toggleVisibility'])->name('user_change_visibility');
            });


    });



    /*
    |-------------------------------------------------------------------------------
    | Auth Routes
    |-------------------------------------------------------------------------------
    | Prefix:         NONE
    | Controller:     RegisteredUserController, AuthenticatedSessionController, PasswordResetLinkController
    | Method:         MIXED
    | Description:    Auth routes
    */
    require __DIR__.'/auth.php';

}catch (\Throwable $e){
    Log::error($e->getMessage());
    return view('welcome');
}

resources/views/layouts/admin/footer.blade.php
<footer class="py-4 bg-light mt-auto">
    <div class="container-fluid px-4">
        <div class="d-flex align-items-center justify-content-between small">
            <div class="text-muted">Copyright &copy; {{ config('app.name', 'Coin App') }} {{ date('Y') }}</div>
            <div>
                <a href="#">Privacy Policy</a>
                &middot;
                <a href="#">Terms &amp; Conditions</a>
            </div>
        </div>
    </div>
</footer>

resources/views/layouts/admin/main.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name', 'Coin App') }}</title>

    @include('layouts.styles')


    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>



</head>
<body class="sb-nav-fixed">

@include('layouts.admin.top-nav')
<div id="layoutSidenav">
    @include('layouts.admin.side-nav')
    <div id="layoutSidenav_content">
        <main>
            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @if (session('error'))
                <div class="alert alert-danger">
                    {{ session('error') }}
                </div>
            @endif
                @if (session('status'))
                    <div class="alert alert-info">
                        {{ session('status') }}
                    </div>
                @endif
                @if (session('success'))
                    <div class="alert alert-success">
                        <ul>
                            <li>{{ session('success') }}</li>
                        </ul>
                    </div>
                @endif
            <div id="app2" class="container-fluid px-4">
                @stack('header')
                @yield('content')


            </div>
        </main>
        @include('layouts.admin.footer')
    </div>
</div>
@include('layouts.scripts')
</body>
</html>

resources/views/layouts/admin/side-nav.blade.php
<div id="layoutSidenav_nav">
    <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
        <div class="sb-sidenav-menu">
            <div class="nav">
                <div class="sb-sidenav-menu-heading">Core</div>
                <a class="nav-link" href="{{ route('user.dashboard') }}">
                    <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                    User Area
                </a>
                <div class="sb-sidenav-menu-heading">Interface</div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapseLayouts" aria-expanded="false" aria-controls="collapseLayouts">
                    <div class="sb-nav-link-icon"><i class="fas fa-columns"></i></div>
                    User Mgt
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapseLayouts" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav">
                        <a class="nav-link" href="layout-static.html">Clone</a>
                        <a class="nav-link" href="layout-sidenav-light.html">Lightidenav</a>
                    </nav>
                </div>
                <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#collapsePages" aria-expanded="false" aria-controls="collapsePages">
                    <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                    Pages
                    <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                </a>
                <div class="collapse" id="collapsePages" aria-labelledby="headingTwo" data-bs-parent="#sidenavAccordion">
                    <nav class="sb-sidenav-menu-nested nav accordion" id="sidenavAccordionPages">
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseAuth" aria-expanded="false" aria-controls="pagesCollapseAuth">
                            Authentication
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="pagesCollapseAuth" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="login.html">Login</a>
                                <a class="nav-link" href="register.html">Register</a>
                                <a class="nav-link" href="password.html">Forgot Password</a>
                            </nav>
                        </div>
                        <a class="nav-link collapsed" href="#" data-bs-toggle="collapse" data-bs-target="#pagesCollapseError" aria-expanded="false" aria-controls="pagesCollapseError">
                            Error
                            <div class="sb-sidenav-collapse-arrow"><i class="fas fa-angle-down"></i></div>
                        </a>
                        <div class="collapse" id="pagesCollapseError" aria-labelledby="headingOne" data-bs-parent="#sidenavAccordionPages">
                            <nav class="sb-sidenav-menu-nested nav">
                                <a class="nav-link" href="401.html">401 Page</a>
                                <a class="nav-link" href="404.html">404 Page</a>
                                <a class="nav-link" href="500.html">500 Page</a>
                            </nav>
                        </div>
                    </nav>
                </div>
                <div class="sb-sidenav-menu-heading">Addons</div>
                <a class="nav-link" href="charts.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                    Charts
                </a>
                <a class="nav-link" href="tables.html">
                    <div class="sb-nav-link-icon"><i class="fas fa-table"></i></div>
                    Tables
                </a>
            </div>
        </div>
        <div class="sb-sidenav-footer">
            <div class="small">Logged in as: {{ auth()->user()->name }}</div>
        </div>
    </nav>
</div>

resources/views/layouts/admin/top-nav.blade.php
<nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
    <!-- Navbar Brand-->
    <a class="navbar-brand ps-3" href="{{ route('user.dashboard') }}">{{ config('app.name', 'Coin App') }}</a>
    <!-- Sidebar Toggle-->
    <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
    <!-- Navbar Search-->
    <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0" id="find_user" action="{{ route('admin.find_user') }}" method="post">
        @csrf
        <div class="input-group">
            <input name="searchTerm" class="form-control" type="text" placeholder="Find User..." aria-label="Find User..." aria-describedby="btnNavbarSearch" />
            <button class="btn btn-primary" id="btnNavbarSearch" type="submit"><i class="fas fa-search"></i></button>
        </div>
    </form>
    <!-- Navbar-->
    <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>
            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                @if (auth()->user()->is_admin)
                    <li><a class="dropdown-item" href="{{ route('admin.dashboard') }}">Admin Area</a></li>
                @endif
                <li><a class="dropdown-item" href="{{ route('user.dashboard') }}">Settings</a></li>
                <li><a class="dropdown-item" href="{{ route('user.dashboard') }}">Activity Log</a></li>
                <li><hr class="dropdown-divider" /></li>
                <li><a class="dropdown-item" href="#!" onclick="event.preventDefault(); document.getElementById('logout-form').submit();">Logout</a></li>
            </ul>
        </li>
    </ul>
    <form id="logout-form" method="POST" action="{{ route('logout') }}" style="display: none;">
        @csrf
    </form>
</nav>